### ISSUE TITLE
Security Dashboard as Issue

### ISSUE THREAD

**Issue by marwin1991** [angrymeir/SecScanner2JUnit#21]
**Describe the idea**
- Dashboard to summarize vulnerabilities in "default" branch 
- Something like: https://github.com/marwin1991/profile-technology-icons/issues/11

**How to implement?**
- All artifacts as XML from previous jobs should be pass to new job
- Read all JUNIT Xml and create a table or circle diagram ?

**Comment by marwin1991** [comment]
https://docs.bmc.com/docs/vulnerabilitymanagement/31/security-dashboard-821945865.html

**Comment by angrymeir** [comment]
Definitely a cool idea to generate better insights into the current security state of a project!
But I think it would make sense to provide this functionality through a different project/tool for two reasons:

## 1. Completeness
Most projects I know/worked in employ more than only GitLab's security scanning features or they employ multiple different tools for the same use-case (e.g. Trivy and Snyk for SCA). If one would like to have a complete overview on the current security state, it would be necessary to also include their output. And that's out of scope for SecScanner2Junit... 

## 2. Compactness
I'm a big fan of the UNIX philosophy "Make each program do one thing well [...]" and "Expect the output of every program to become the input to another, [...]". I fear, the more features we implement, the more complicated and harder to maintain it gets...

But I'll definitely help to build the new tool :)

Btw: Did you have a look at something like [DefectDojo](https://www.defectdojo.org)? Not sure, whether the output of SecScanner2Junit could be imported, but if possible DefectDojo already has nice visualizations and the additional advantage of vulnerability tracing.

**Comment by marwin1991** [comment]
I've started new project: https://github.com/logchange/eir

The main idea is to create extensible system, that will be easy to add new inputs that all thath will be collect to one report as MD file f.e. as an issue :) Maybe it will be crap or something useful :)
