### ISSUE TITLE
Report only recognised when prefixed with current directory (./)

### ISSUE THREAD

**Issue by angrymeir** [angrymeir/SecScanner2JUnit#3]
@angrymeir 
after an update I've got error:

![image](https://user-images.githubusercontent.com/25181517/175073525-4e7755ed-a642-4f66-8316-0966624fddc1.png)
I have re-run but still the same (file was for sure, because it is commited to repo to tests)

I've mange to solve it with:
```
    - ss2ju sast ./gl-sast-report.json gl-sast-report.xml
```

It is only FYI maybe you will have the same problem :)

Anyway thank you so much!

_Originally posted by @marwin1991 in https://github.com/angrymeir/SecScanner2JUnit/issues/2#issuecomment-1163278033_

**Comment by marwin1991** [comment]
This was my bad, I was using commited file to repo to so tests and used
```
    GIT_STRATEGY: none
```
What caused that not always there was repo cloned.

We can close this issue then :)
