### ISSUE TITLE
Testcases with same name overwrite each other

### ISSUE THREAD

**Issue by angrymeir** [angrymeir/SecScanner2JUnit#9]
### Issue description

Testcases with the same name in a Testsuite overwrite each other in GitLab. So this is not a Bug of SecScanner2Junit, but rather expected behavior of GitLab is guess. However, we can circumvent this problem by making the testcase names unique on our side.

### Steps to reproduce the issue

1. Upload a report with two findings from the same scanner with the same name (see below for example report)
2. Check JUnit tests on GitLab

### What's the expected result?

- Both findings will appear

### What's the actual result?

- Only the latter finding in the report will appear on GitLab

### Additional details

Example report:
```xml
<?xml version="1.0" ?>
<testsuites disabled="0" errors="0" failures="2" tests="2" time="0.0">
	<testsuite disabled="0" errors="0" failures="2" name="gl-sast-report" skipped="0" tests="2" time="0">
		<testcase name="TestCaseName" classname="SAST" file="filenameA">
			<failure type="Failure Type" message="Oh boy, something went wrong">Well well well</failure>
		</testcase>
		<testcase name="TestCaseName" classname="SAST" file="filenameB">
			<failure type="Failure Type" message="Oh boy, something went wrong">Well well well</failure>
		</testcase>
	</testsuite>
</testsuites>
```

**Comment by marwin1991** [comment]
Every vulnerability has also id, so maybe we can concat it with name?
